# Generated by Django 3.0.9 on 2021-07-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmailPreview',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('emails.email',),
        ),
    ]
