# Generated by Django 3.0.4 on 2020-06-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='storage',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='static_assets.StorageBackend'),
            preserve_default=False,
        ),
    ]
