# Generated by Django 3.0.4 on 2020-06-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('films', '0002_film_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='films.Asset'
                    ),
                ),
                (
                    'comment',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.ManyToManyField(
                related_name='asset', through='films.AssetComment', to='comments.Comment'
            ),
        ),
    ]
