# Generated by Django 3.0.4 on 2020-06-03 15:52

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20200603_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='picture_16_9',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=models.ImageField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_16_9',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
