# Generated by Django 3.0.8 on 2020-07-08 09:19

import assets.models.assets
import common.upload_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20200603_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='picture_16_9',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=models.ImageField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_16_9',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.TextField(choices=[('0_dev', 'In Development'), ('1_prod', 'In Production'), ('2_released', 'Released')]),
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='visibility',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='visibility',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='film',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=models.ImageField(default=43, upload_to=common.upload_paths.get_upload_to_hashed_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='film',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='films.Film'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='film',
            old_name='storage',
            new_name='storage_backend',
        ),
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_16_9',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_ordering_per_collection',
        ),
        migrations.AlterField(
            model_name='asset',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='picture_16_9',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='collection',
            name='preview',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
