# Generated by Django 3.0.4 on 2020-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_add_film_release_date_and_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.TextField(choices=[('0_dev', 'In Development'), ('1_prod', 'In Production'), ('2_released', 'Released')]),
        ),
    ]
