# Generated by Django 3.0.4 on 2020-06-08 12:58

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_rename_film_status_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='visibility',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='visibility',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='watch_link',
            new_name='youtube_link',
        ),
        migrations.AddField(
            model_name='collection',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=models.ImageField(default=43, upload_to=common.upload_paths.get_upload_to_hashed_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
