# Generated by Django 3.0.4 on 2020-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20200608_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
