# Generated by Django 3.0.4 on 2020-06-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_asset_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='film',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='films.Film'),
            preserve_default=False,
        ),
    ]
