# Generated by Django 3.0.4 on 2020-06-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_asset_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='storage',
            new_name='storage_backend',
        ),
    ]
