# Generated by Django 3.0.4 on 2020-06-14 15:52

import assets.models.assets
import common.upload_paths
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_rename_storage_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_16_9',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
