# Generated by Django 3.0.4 on 2020-06-14 23:09

import assets.models.assets
import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_add_dynamic_file_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_ordering_per_collection',
        ),
        migrations.AlterField(
            model_name='asset',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='picture_16_9',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='collection',
            name='preview',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
