# Generated by Django 3.0.4 on 2020-06-14 23:17

from django.db import migrations, models
import django.db.models.deletion


def set_backend_collection(apps, schema_editor):
    Collection = apps.get_model('films', 'Collection')
    for collection in Collection.objects.all().iterator():
        collection.storage_backend = collection.film.storage_backend
        collection.save()


def reverse_func(apps, schema_editor):
    pass  # Nothing do to


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_rename_storage_backend'),
        ('films', '0012_order_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='storage_backend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.StorageBackend'),
            preserve_default=False,
        ),
        migrations.RunPython(set_backend_collection, reverse_func),
        migrations.AlterField(
            model_name='collection',
            name='storage_backend',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE,
                                    to='assets.StorageBackend'),
        ),
    ]
