# Generated by Django 3.0.4 on 2020-06-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_production_log_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionlogentry',
            options={'verbose_name_plural': 'production log entries'},
        ),
    ]
