# Generated by Django 3.0.4 on 2020-06-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_production_name_entries_plural_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionlogentry',
            old_name='log_group',
            new_name='production_log',
        ),
    ]
