# Generated by Django 3.0.4 on 2020-06-18 07:50

import assets.models.assets
import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_rename_log_group_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='picture_16_9',
            field=assets.models.assets.DynamicStorageFileField(default='', upload_to=common.upload_paths.get_upload_to_hashed_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionlog',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
