# Generated by Django 3.0.4 on 2020-06-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_source_preview_as_dynamic_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0018_productionlog_add_name_picture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='storage_backend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='assets.StorageBackend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
