# Generated by Django 3.0.8 on 2020-07-08 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0015_squashed_0019_production_log_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionlogentryasset',
            name='production_log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_assets', to='films.ProductionLogEntry'),
        ),
        migrations.AlterModelOptions(
            name='productionlog',
            options={'verbose_name': 'production weekly', 'verbose_name_plural': 'production weeklies'},
        ),
        migrations.AlterModelOptions(
            name='productionlogentry',
            options={'verbose_name': 'production weekly entry', 'verbose_name_plural': 'production weekly entries'},
        ),
        migrations.AlterModelOptions(
            name='productionlogentryasset',
            options={'verbose_name': 'production weekly entry asset'},
        ),
        migrations.AlterField(
            model_name='productionlogentry',
            name='production_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='films.ProductionLog', verbose_name='production weekly'),
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_production_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_production_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionlogentryasset',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_asset', to='films.Asset'),
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='storage_backend',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='storage_backend',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='storage_backend',
            new_name='storage_location',
        ),
    ]
