# Generated by Django 3.0.4 on 2020-06-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_add_storage_backend_to_production_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
