# Generated by Django 3.0.4 on 2020-06-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_productionlogentryasset_related_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionlog',
            options={'verbose_name': 'production weekly', 'verbose_name_plural': 'production weeklies'},
        ),
        migrations.AlterModelOptions(
            name='productionlogentry',
            options={'verbose_name': 'production weekly entry', 'verbose_name_plural': 'production weekly entries'},
        ),
        migrations.AlterModelOptions(
            name='productionlogentryasset',
            options={'verbose_name': 'production weekly entry asset'},
        ),
        migrations.AlterField(
            model_name='productionlogentry',
            name='production_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='films.ProductionLog', verbose_name='production weekly'),
        ),
    ]
