# Generated by Django 3.0.4 on 2020-06-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_productionlog_author_and_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlogentryasset',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_asset', to='films.Asset'),
        ),
    ]
