# Generated by Django 3.0.8 on 2020-07-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_productionlogentryasset_related_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='storage_backend',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='storage_backend',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='storage_backend',
            new_name='storage_location',
        ),
    ]
