# Generated by Django 3.0.8 on 2020-07-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_asset_contains_blend_file'),
    ]

    operations = [
        migrations.RemoveField(model_name='productionlogentry', name='author_role',),
    ]
