# Generated by Django 3.0.9 on 2020-08-25 10:26

import common.upload_paths
from django.db import migrations
import static_assets.models.static_assets


def set_default_picture_16_9(apps, schema_editor):
    Film = apps.get_model('films', 'Film')
    for film in Film.objects.filter(picture_16_9=''):
        film.picture_16_9 = film.picture_header
        film.save()


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0030_asset_is_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection', old_name='picture_16_9', new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='productionlog', old_name='picture_16_9', new_name='thumbnail',
        ),
        migrations.RunPython(set_default_picture_16_9, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='film',
            name='picture_16_9',
            field=static_assets.models.static_assets.DynamicStorageFileField(
                upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.RenameField(model_name='film', old_name='picture_16_9', new_name='thumbnail',),
    ]
