# Generated by Django 3.0.9 on 2020-08-24 16:18

import common.upload_paths
from django.db import migrations
import static_assets.models.static_assets


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0030_asset_is_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='picture_16_9',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='picture_16_9',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='film',
            name='picture_16_9',
        ),
        migrations.AddField(
            model_name='film',
            name='thumbnail',
            field=static_assets.models.static_assets.DynamicStorageFileField(default='', upload_to=common.upload_paths.get_upload_to_hashed_path),
            preserve_default=False,
        ),
    ]
