# Generated by Django 3.0.9 on 2020-09-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0031_thumbnail_fields'),
    ]

    operations = [
        migrations.RunSQL(r'''
        update films_film
        set logo = regexp_replace(logo, '[_/]*(\w{2})(\w+)\.(\w+)', '\1/\1\2/\1\2.\3')
        where logo like '_/%.%'
        '''),
        migrations.RunSQL(r'''
        update films_film
        set thumbnail = regexp_replace(thumbnail, '[_/]*(\w{2})(\w+)\.(\w+)', '\1/\1\2/\1\2.\3')
        where thumbnail like '_/%.%'
        '''),
        migrations.RunSQL(r'''
        update films_film
        set picture_header = regexp_replace(picture_header, '[_/]*(\w{2})(\w+)\.(\w+)', '\1/\1\2/\1\2.\3')
        where picture_header like '_/%.%'
        '''),
        migrations.RunSQL(r'''
        update films_film
        set poster = regexp_replace(poster, '[_/]*(\w{2})(\w+)\.(\w+)', '\1/\1\2/\1\2.\3')
        where poster like '_/%.%'
        '''),

        migrations.RunSQL(r'''
        update films_collection
        set preview = regexp_replace(preview, '[_/]*(\w{2})/(\w+)\.(\w+)', '\1/\2/\2.\3')
        where preview like '_/%/%.%'
        '''),
        migrations.RunSQL(r'''
        update films_collection
        set preview = regexp_replace(preview, '[_/]*(\w{2})(\w+)\.(\w+)', '\1/\1\2/\1\2.\3')
        where preview like '_/%.%'
        '''),
    ]
