# Generated by Django 3.0.9 on 2020-09-22 15:35

from django.db import migrations


def copy_preview_to_thumbnail(apps, schema_editor):
    Collection = apps.get_model('films', 'Collection')
    for collection in Collection.objects.all():
        collection.thumbnail.name = collection.preview.name
        collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0032_normalise_file_paths'),
    ]

    operations = [
        migrations.RunPython(copy_preview_to_thumbnail, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='collection',
            name='preview',
        ),
    ]
