# Generated by Django 3.0.9 on 2020-09-23 07:43

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0033_preview_to_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='thumbnail',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
