# Generated by Django 3.0.10 on 2020-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0034_update_file_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='film',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='storage_location',
        ),
    ]
