# Generated by Django 3.0.9 on 2020-10-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0026_increase_file_field_max_lenght'),
        ('films', '0036_collection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='static_asset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                to='static_assets.StaticAsset',
            ),
        ),
    ]
