# Generated by Django 3.0.9 on 2020-10-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0037_nullable_static_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(name='film', options={'ordering': ('-release_date',)},),
    ]
