# Generated by Django 3.0.9 on 2020-10-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
        ('films', '0039_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmflatpage',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='static_assets.StaticAsset'),
        ),
    ]
