# Generated by Django 3.0.9 on 2020-10-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0040_nullable_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(name='collection', options={'ordering': ['-date_created']},),
    ]
