# Generated by Django 3.0.9 on 2020-10-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
        ('films', '0041_collections_default_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='attachments',
            field=models.ManyToManyField(
                blank=True, related_name='_asset_attachments_+', to='static_assets.StaticAsset'
            ),
        ),
    ]
