# Generated by Django 3.0.9 on 2020-10-25 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0042_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionlog',
            options={'verbose_name': 'production log', 'verbose_name_plural': 'production logs'},
        ),
        migrations.AlterModelOptions(
            name='productionlogentry',
            options={'verbose_name': 'production log entry', 'verbose_name_plural': 'production log entries'},
        ),
        migrations.AlterModelOptions(
            name='productionlogentryasset',
            options={'verbose_name': 'production log entry asset'},
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The actual author of the summary in the production log', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_production_logs', to=settings.AUTH_USER_MODEL, verbose_name='author (optional)'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='name',
            field=models.CharField(blank=True, help_text='If not provided, will be set to <em>"This week on [film title]"</em>.', max_length=512, verbose_name='production log title'),
        ),
        migrations.AlterField(
            model_name='productionlogentry',
            name='production_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='films.ProductionLog', verbose_name='production log'),
        ),
    ]
