# Generated by Django 3.0.9 on 2020-10-26 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0043_weeklies_to_production_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcrew',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
