# Generated by Django 3.0.9 on 2020-10-26 00:48

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0044_film_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
