# Generated by Django 3.0.9 on 2020-10-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0045_blank_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlogentry',
            name='legacy_id',
            field=models.SlugField(blank=True),
        ),
    ]
