# Generated by Django 3.0.9 on 2020-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0047_optional_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['order', 'date_created']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order', 'date_created']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, help_text='Format the content in <a href="https://commonmark.org/help/">Markdown</a>.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='text',
            field=models.TextField(blank=True, help_text='Format the content in <a href="https://commonmark.org/help/">Markdown</a>.'),
        ),
    ]
