# Generated by Django 3.0.9 on 2020-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0050_add_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='show_production_logs_as_featured',
            field=models.BooleanField(default=False, help_text='Display production logs instead of the featured gallery on the film page.'),
        ),
        migrations.AddField(
            model_name='film',
            name='show_production_logs_nav_link',
            field=models.BooleanField(default=False, help_text='Display a link to production logs in the navigation.'),
        ),
    ]
