# Generated by Django 3.0.9 on 2020-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0051_add_show_production_logs_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlogentry',
            name='assets',
            field=models.ManyToManyField(through='films.ProductionLogEntryAsset', to='films.Asset'),
        ),
    ]
