# Generated by Django 3.0.9 on 2020-12-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
        ('films', '0052_add_production_log_assets_thu_nosql'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAsset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('static_assets.staticasset',),
        ),
    ]
