# Generated by Django 3.0.9 on 2020-12-03 16:40

from django.db import migrations, models
import django.utils.timezone


def copy_earliest_date_created_to_date_published(apps, schema_editor):
    Asset = apps.get_model('films', 'Asset')
    for asset in Asset.objects.all():
        dates = [asset.date_created]
        if asset.static_asset:
            dates.append(asset.static_asset.date_created)
        asset.date_published = min(dates)
        asset.date_created = asset.date_published
        asset.save(update_fields=['date_created', 'date_published'])
        # Since we are here anyway, let's use this opportunity to set the earliest available date_created
        if asset.static_asset and asset.date_published < asset.static_asset.date_created:
            asset.static_asset.date_created = asset.date_published
            asset.static_asset.save(update_fields=['date_created'])


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0053_add_proxy_model_for_upload_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(copy_earliest_date_created_to_date_published, reverse_code=migrations.RunPython.noop)
    ]
