# Generated by Django 3.0.9 on 2020-12-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0054_add_date_published_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['order', 'date_published']},
        ),
    ]
