# Generated by Django 3.0.9 on 2020-12-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0055_asset_meta_ordering_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
