# Generated by Django 3.0.9 on 2020-12-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0058_production_log_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionlogentry',
            options={'ordering': ['id'], 'verbose_name': 'production log entry', 'verbose_name_plural': 'production log entries'},
        ),
    ]
