# Generated by Django 3.0.9 on 2020-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0060_markdown_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='show_blog_posts',
            field=models.BooleanField(default=False, help_text='Display latest blog posts on the film page.'),
        ),
    ]
