# Generated by Django 3.0.9 on 2020-09-29 12:12

import common.upload_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='profile',
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                (
                    'avatar',
                    models.ImageField(
                        blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
    ]
