# Generated by Django 3.0.9 on 2020-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
