# Generated by Django 3.0.9 on 2020-12-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_move_profile_fields'),
        ('profiles', '0002_auto_20201218_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
