# Generated by Django 3.0.9 on 2020-12-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_profile'),
    ]
    
    database_operations = [
        migrations.AlterModelTable('Notification', 'users_notification')
    ]

    state_operations = [
        migrations.DeleteModel('Notification')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
