# Generated by Django 3.0.9 on 2020-10-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blender_id_oauth_client', '0002_oauth_user_info'),
        ('profiles', '0003_drop_avatar_field'),
    ]

    operations = [
        # FIXME(anna): because this table is en external dependency,
        # there's no other way to enforce this contraint
        # Addin OAuthUserInfo._meta.get_field('oauth_user_id')._unique = True
        # would generate a migration inside `blender_id_oauth_client`
        migrations.RunSQL(
            # Generated with sqlmigrate from an automatic migration that was removed right after
            # e.g. if blender_id_oauth_client migration number is NNNN
            sql=[
                # ./manage.py sqlmigrate blender_id_oauth_client NNNN
                'ALTER TABLE "blender_id_oauth_client_oauthuserinfo" '
                'ADD CONSTRAINT "blender_id_oauth_client__oauth_user_id_b1e52371_uniq" '
                'UNIQUE ("oauth_user_id");',
                'CREATE INDEX "blender_id_oauth_client__oauth_user_id_b1e52371_like" '
                'ON "blender_id_oauth_client_oauthuserinfo" ("oauth_user_id" varchar_pattern_ops);',
            ],
            reverse_sql=[
                # ./manage.py sqlmigrate blender_id_oauth_client NNNN --backwards
                'DROP INDEX IF EXISTS "blender_id_oauth_client__oauth_user_id_b1e52371_like";',
                'ALTER TABLE "blender_id_oauth_client_oauthuserinfo" '
                'DROP CONSTRAINT IF EXISTS "blender_id_oauth_client__oauth_user_id_b1e52371_uniq";',
            ],
        ),
    ]
