# Generated by Django 3.0.9 on 2021-01-06 11:42

from django.db import migrations
import logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def replace_profiles_can_view_content_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('users', 'User')
    content_type_user = ContentType.objects.get_for_model(User)
    old_permission = Permission.objects.filter(
        codename='can_view_content',
        content_type=ContentType.objects.get(app_label='profiles', model='profile'),
    ).first()
    new_permission, _ = Permission.objects.get_or_create(
        codename='can_view_content',
        content_type=content_type_user,
        name='Can view subscription-only content',
    )
    for group_name in ('demo', 'subscriber', '_org_member'):
        # Create these groups, so that tests and newly setup dev environments worked as expected
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(new_permission)
        if old_permission:
            group.permissions.remove(old_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_badges'),
    ]

    operations = [
        migrations.RunPython(replace_profiles_can_view_content_permission),
    ]
