# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
exclude: 'migrations/|studio/settings'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.11.0
    hooks:
    -   id: eslint

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies: ['flake8-docstrings==1.5.0']

  - repo: https://github.com/rtts/djhtml
    rev: v1.4.0
    hooks:
    - id: djhtml
      args: [--tabwidth=2]
