# Generated by Django 3.0.14 on 2021-10-25 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_add_is_published_is_free_to_character_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterversion',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
