# Generated by Django 3.0.14 on 2021-10-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_add_fields_to_showcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='is_free',
        ),
    ]
