# Generated by Django 3.0.14 on 2021-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactershowcase',
            name='preview_youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='preview_youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
