# Generated by Django 3.0.14 on 2021-10-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_add_preview_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='view_count',
        ),
    ]
