# Generated by Django 3.0.14 on 2021-11-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0011_add_static_asset_view_download_count'),
        ('characters', '0007_remove_character_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactershowcase',
            name='preview_video_static_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='static_assets.StaticAsset'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='preview_video_static_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='static_assets.StaticAsset'),
        ),
    ]
