# Generated by Django 3.0 on 2020-02-14 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import training_main.models.sections


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                (
                    'chapter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sections',
                        to='training_main.Chapter',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                (
                    'status',
                    models.TextField(
                        choices=[('published', 'Published'), ('unpublished', 'Unpublished')]
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('workshop', 'Workshop'),
                            ('course', 'Course'),
                            ('production_lesson', 'Production Lesson'),
                        ]
                    ),
                ),
                (
                    'difficulty',
                    models.TextField(
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.FileField(upload_to=training_main.models.sections.video_upload_path),
                ),
                ('size', models.IntegerField()),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('position', models.DurationField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='video_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress',
                        to='training_main.Video',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserSectionProgress',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('started', models.BooleanField()),
                ('finished', models.BooleanField()),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress',
                        to='training_main.Section',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='section_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='training_main.Tag'
                    ),
                ),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='training_main.Training'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='tags',
            field=models.ManyToManyField(
                related_name='trainings',
                through='training_main.TrainingTag',
                to='training_main.Tag',
            ),
        ),
        migrations.AddField(
            model_name='section',
            name='video',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='section',
                to='training_main.Video',
            ),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='training_main.Comment'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to='training_main.Training',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(
                related_name='liked_comments',
                through='training_main.Like',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='replies',
                to='training_main.Comment',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='section',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='training_main.Section',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='chapter',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chapters',
                to='training_main.Training',
            ),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.FileField(upload_to=training_main.models.sections.asset_upload_path),
                ),
                ('size', models.IntegerField()),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assets',
                        to='training_main.Section',
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.AddConstraint(
            model_name='uservideoprogress',
            constraint=models.UniqueConstraint(
                fields=('user', 'video'), name='unique_progress_per_user_and_video'
            ),
        ),
        migrations.AddConstraint(
            model_name='usersectionprogress',
            constraint=models.UniqueConstraint(
                fields=('user', 'section'), name='unique_progress_per_user_and_section'
            ),
        ),
        migrations.AddConstraint(
            model_name='trainingtag',
            constraint=models.UniqueConstraint(
                fields=('training', 'tag'), name='unique_tags_per_training'
            ),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(
                fields=['status', 'type', 'difficulty'], name='training_ma_status_b71843_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(
                fields=['status', 'difficulty', 'type'], name='training_ma_status_6b2ae1_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(
                fields=('chapter', 'index'), name='unique_index_per_section'
            ),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(
                fields=('user', 'comment'), name='only_one_like_per_comment_and_user'
            ),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('user', 'training'), name='unique_favourite_per_user_and_training'
            ),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(
                fields=('training', 'index'), name='unique_index_per_chapter'
            ),
        ),
    ]
