# Generated by Django 3.0 on 2020-02-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('training_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='section', name='video'),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='video',
                to='training_main.Section',
            ),
            preserve_default=False,
        ),
    ]
