# Generated by Django 3.0 on 2020-02-21 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_main', '0002_make_video_point_to_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=100)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersectionprogress',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersectionprogress',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
