# Generated by Django 3.0 on 2020-02-25 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('training_main', '0003_progress_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('moderate_comment', 'Can moderate comments')]},
        ),
    ]
