# Generated by Django 3.0.9 on 2020-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('comments_count', models.PositiveIntegerField(blank=True, null=True)),
                ('film_assets_count', models.PositiveIntegerField(blank=True, null=True)),
                ('blog_posts_count', models.PositiveIntegerField(blank=True, null=True)),
                ('users_total_count', models.PositiveIntegerField(blank=True, null=True)),
                ('users_subscribers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('users_demo_count', models.PositiveIntegerField(blank=True, null=True)),
                ('training_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('legacy_id', models.SlugField(blank=True)),
            ],
            options={
                'db_table': 'stats',
                'ordering': ['timestamp'],
            },
        ),
    ]
