# Generated by Django 3.0.9 on 2021-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='blog_posts_count',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='film_assets_count',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='training_seconds',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='users_demo_count',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='users_subscribers_count',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='users_total_count',
        ),
        migrations.AddField(
            model_name='sample',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='legacy_id',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['slug'], name='stats_slug_c12c93_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['timestamp', 'slug', 'value'], name='stats_timesta_d1e8a0_idx'),
        ),
    ]
