# Generated by Django 3.0.8 on 2020-07-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('assets', '0002_auto_20200602_0745'), ('assets', '0003_auto_20200603_0859')]

    dependencies = [
        ('films', '0001_initial'),
        ('assets', '0001_initial'),
        ('training', '0006_update_unique_constraints'),
    ]

    operations = [
    ]
