# Generated by Django 3.0.4 on 2020-06-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_update_unique_constraints'),
        ('films', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebackend',
            name='film',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Film'),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Training'),
        ),
    ]
