# Generated by Django 3.0.4 on 2020-06-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='preview',
            new_name='picture_16_9',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='preview',
            new_name='picture_16_9',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='preview',
            new_name='picture_16_9',
        ),
        migrations.AddField(
            model_name='file',
            name='original_filename',
            field=models.CharField(default='whatever', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(default='whatever', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(default='whatever', max_length=128),
            preserve_default=False,
        ),
    ]
