# Generated by Django 3.0.4 on 2020-06-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('training', '0006_update_unique_constraints'),
        ('assets', '0002_auto_20200601_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('film', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Film')),
                ('training', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Training')),
            ],
        ),
    ]
