# Generated by Django 3.0.4 on 2020-06-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_auto_20200603_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='original_filename',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='size_bytes',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='play_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
