# Generated by Django 3.0.8 on 2020-07-08 09:16

import assets.models.assets
import common.upload_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('assets', '0004_auto_20200608_1258'), ('assets', '0005_storage_backends'), ('assets', '0006_rename_storage_backend'), ('assets', '0007_big_integer_field'), ('assets', '0008_static_asset_preview'), ('assets', '0009_source_preview_as_dynamic_file'), ('assets', '0010_rename_static_asset_duration')]

    dependencies = [
        ('assets', '0003_auto_20200603_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='original_filename',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='size_bytes',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='play_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='category',
            field=models.CharField(choices=[('local', 'Local Storage'), ('gcs', 'Google Cloud Storage')], default='local', max_length=5),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='source',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='source_preview',
            field=assets.models.assets.DynamicStorageFileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='size_bytes',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='source_preview',
            field=models.ImageField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='source_preview',
            field=assets.models.assets.DynamicStorageFileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.RenameField(
            model_name='video',
            old_name='duration_seconds',
            new_name='duration',
        ),
    ]
