# Generated by Django 3.0.4 on 2020-06-12 09:58

import assets.models.assets
import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200608_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebackend',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='category',
            field=models.CharField(choices=[('local', 'Local Storage'), ('gcs', 'Google Cloud Storage')], default='local', max_length=5),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='source',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
