# Generated by Django 3.0.4 on 2020-06-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_rename_storage_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='size_bytes',
            field=models.BigIntegerField(editable=False),
        ),
    ]
