# Generated by Django 3.0.4 on 2020-06-15 00:18

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_big_integer_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='source_preview',
            field=models.ImageField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
