# Generated by Django 3.0.8 on 2020-07-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_source_preview_as_dynamic_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='duration_seconds',
            new_name='duration',
        ),
    ]
