# Generated by Django 3.0.8 on 2020-07-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_productionlogentryasset_related_name'),
        ('training', '0015_alter_video_size_bytes'),
        ('assets', '0010_rename_static_asset_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageBackend',
            new_name='StorageLocation',
        ),
    ]
