# Generated by Django 3.0.8 on 2020-07-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('assets', '0011_rename_storage_backend'), ('assets', '0012_rename_storage_backend_fields')]

    dependencies = [
        ('films', '0024_productionlogentryasset_related_name'),
        ('training', '0015_alter_video_size_bytes'),
        ('assets', '0010_rename_static_asset_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageBackend',
            new_name='StorageLocation',
        ),
        migrations.RenameField(
            model_name='staticasset',
            old_name='storage_backend',
            new_name='storage_location',
        ),
    ]
