# Generated by Django 3.0.8 on 2020-07-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_rename_storage_backend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticasset',
            old_name='storage_backend',
            new_name='storage_location',
        ),
    ]
