# Generated by Django 3.0.9 on 2020-10-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_cascade_comment_replies_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
