# Generated by Django 3.0.9 on 2020-10-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comments_add_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
