# Generated by Django 3.0.9 on 2020-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comments_blank_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment', name='message_html', field=models.TextField(blank=True),
        ),
    ]
