# Generated by Django 3.0.9 on 2020-12-18 10:35

import common.mixins
import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=256)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=512)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('excerpt', models.TextField(blank=True, help_text='An optional short description displayed on the blog card.')),
                ('content', models.TextField()),
                ('content_html', models.TextField(blank=True, editable=False)),
                ('thumbnail', models.FileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path)),
                ('header', models.FileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path)),
            ],
            options={
                'ordering': ('-date_published',),
            },
            bases=(common.mixins.StaticThumbnailURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
