# Generated by Django 3.0.9 on 2020-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_assets', '0001_initial'),
        ('blog', '0002_auto_20201218_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='static_assets.StaticAsset'),
        ),
    ]
