# Generated by Django 3.0.8 on 2020-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_subtitle_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='topic',
            field=models.CharField(default='Recent Update', max_length=128),
            preserve_default=False,
        ),
    ]
