# Generated by Django 3.0.9 on 2020-08-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_revision_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision', old_name='picture_16_9', new_name='thumbnail',
        ),
    ]
