# Generated by Django 3.0.9 on 2020-09-23 07:43

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_revision_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='thumbnail',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
