# Generated by Django 3.0.9 on 2020-10-23 00:59

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_storage_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='header',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AlterField(
            model_name='revision',
            name='thumbnail',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
    ]
