# Generated by Django 3.0.9 on 2020-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_revision_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post', name='legacy_id', field=models.CharField(blank=True, max_length=256),
        ),
    ]
