# Generated by Django 3.0.9 on 2020-10-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
        ('blog', '0008_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='static_assets.StaticAsset'),
        ),
    ]
