# Generated by Django 3.0.9 on 2020-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post', name='slug', field=models.SlugField(max_length=128),
        ),
    ]
