# Generated by Django 3.0.9 on 2020-11-06 23:46

from dataclasses import dataclass
import common.upload_paths
from django.db import migrations, models
from django.db import connection


def move_properties_from_latest_revision(apps, schema_editor):
    """Transfer the latest revision attributes to the Post object."""
    Post = apps.get_model('blog', 'Post')

    @dataclass
    class Revision:
        """Stand-in representation of the delete Revision model."""

        title: str
        topic: str
        content: str
        content_html: str
        description: str
        header: str
        thumbnail: str

    def fetch_latest_revision(post_id):
        """Fetch the latest versions from the blog_revisions table.

        Cast the revision row into the Revision object for clarity.
        """
        print(f"Fetching post {post_id}")
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT title, topic, content, html_content, description, header, thumbnail "
                "FROM blog_revision WHERE post_id = %s ORDER BY date_updated DESC",
                [post_id],
            )
            row = cursor.fetchone()

        return Revision(*row)

    for post in Post.objects.order_by('id'):
        # Transfer the latest revision attributes to the Post object
        revision = fetch_latest_revision(post.id)
        post.title = revision.title
        post.excerpt = revision.description
        post.content = revision.content
        post.content_html = revision.content_html
        post.category = revision.topic
        post.header = revision.header
        post.thumbnail = revision.thumbnail
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post', name='category', field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(
                blank=True, help_text='An optional short description displayed on the blog card.'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.RunPython(
            move_properties_from_latest_revision, reverse_code=migrations.RunPython.noop
        ),
        migrations.DeleteModel(name='Revision'),
    ]
