# Generated by Django 3.0.9 on 2020-11-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_drop_revisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_published',)},
        ),
    ]
