# Generated by Django 3.0.9 on 2020-12-18 10:35

import common.mixins
import common.storage
import common.upload_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_label', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('source', models.FileField(blank=True, max_length=256, storage=common.storage.S3Boto3CustomStorage(), upload_to=common.upload_paths.get_upload_to_hashed_path)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('original_filename', models.CharField(editable=False, max_length=128)),
                ('size_bytes', models.BigIntegerField(editable=False)),
                ('thumbnail', models.FileField(blank=True, max_length=256, upload_to=common.upload_paths.get_upload_to_hashed_path)),
                ('slug', models.SlugField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['-date_created'],
            },
            bases=(common.mixins.StaticThumbnailURLMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('local', 'Local Storage'), ('gcs', 'Google Cloud Storage')], default='local', max_length=5)),
                ('bucket_name', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('position', models.DurationField(help_text='[DD] [[HH:]MM:]ss[.uuuuuu]')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_label', models.CharField(blank=True, max_length=32)),
                ('duration', models.DurationField(help_text='[DD] [[HH:]MM:]ss[.uuuuuu]')),
                ('play_count', models.PositiveIntegerField(default=0, editable=False)),
                ('static_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static_assets.StaticAsset')),
            ],
        ),
        migrations.CreateModel(
            name='VideoVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_label', models.CharField(blank=True, max_length=32)),
                ('source', models.FileField(blank=True, max_length=256, upload_to=common.upload_paths.get_upload_to_hashed_path)),
                ('size_bytes', models.BigIntegerField(editable=False)),
                ('content_type', models.CharField(blank=True, max_length=256)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='static_assets.Video')),
            ],
        ),
    ]
