# Generated by Django 3.0.4 on 2020-06-02 07:45

import static_assets.models.static_assets
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'assets_license',
            },
        ),
        migrations.CreateModel(
            name='StaticAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('source', models.FileField(upload_to=static_assets.models.static_assets.get_upload_to_hashed_path)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('original_filename', models.CharField(max_length=128)),
                ('size_bytes', models.IntegerField()),
                ('source_preview', models.ImageField(blank=True, upload_to=static_assets.models.static_assets.get_upload_to_hashed_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_assets', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_assets', to='static_assets.License')),
            ],
            options={
                'abstract': False,
                'db_table': 'assets_staticasset',
            },
        ),
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'assets_storagelocation',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(blank=True, max_length=32)),
                ('resolution_text', models.CharField(blank=True, max_length=32)),
                ('duration_seconds', models.DurationField(help_text='[DD] [[HH:]MM:]ss[.uuuuuu]')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('static_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static_assets.StaticAsset')),
            ],
            options={
                'abstract': False,
                'db_table': 'assets_video',
            },
        ),
        migrations.AddField(
            model_name='staticasset',
            name='storage_backend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_assets', to='static_assets.StorageBackend'),
        ),
        migrations.AddField(
            model_name='staticasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(blank=True, max_length=32)),
                ('resolution_text', models.CharField(blank=True, max_length=32)),
                ('static_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static_assets.StaticAsset')),
            ],
            options={
                'abstract': False,
                'db_table': 'assets_image',
            },
        ),
    ]
