# Generated by Django 3.0.9 on 2020-12-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0002_auto_20201218_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageLocation',
        ),
    ]
