# Generated by Django 3.0.9 on 2021-08-19 09:58

from django.db import migrations, models
import django.db.models.deletion

import logging
logger = logging.getLogger(__name__)


def set_license(apps, schema_editor):
    StaticAsset = apps.get_model('static_assets', 'StaticAsset')
    License = apps.get_model('static_assets', 'License')
    cc_by = License.objects.filter(slug='cc-by').first()
    if not cc_by:
        logger.error('Unable to retrieve default CC-BY license, not updating any assets')
        return
    count = StaticAsset.objects.filter(license__isnull=True).update(license_id=cc_by.pk)
    logger.warning('Updated %s static assets without license with %s', count, cc_by)


class Migration(migrations.Migration):
    import static_assets.models.static_assets

    dependencies = [
        ('static_assets', '0006_add_contributors_to_static_asset'),
    ]

    operations = [
        migrations.RunPython(set_license, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='staticasset',
            name='license',
            field=models.ForeignKey(default=static_assets.models.static_assets._get_default_license_id, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_assets', to='static_assets.License'),
        ),
    ]
