# Generated by Django 3.0.14 on 2021-10-12 09:56

import common.upload_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0007_add_default_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-US', 'English')], max_length=5)),
                ('source', models.FileField(blank=True, max_length=256, upload_to=common.upload_paths.get_upload_to_hashed_path)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='static_assets.Video')),
            ],
        ),
    ]
