# Generated by Django 3.0.14 on 2021-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0008_subtitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='language_code',
            field=models.CharField(choices=[('en-US', 'English')], max_length=5),
        ),
    ]
