# Generated by Django 3.0.14 on 2021-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0009_more_track_language_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'Video')], default='file', max_length=5),
        ),
    ]
