# Generated by Django 3.0.14 on 2021-10-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0009_set_subtitles_language_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitles',
            old_name='language_code',
            new_name='language',
        ),
    ]
