# Generated by Django 3.0.8 on 2020-07-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_squashed_0025_alter_model_fields_and_options'),
        ('training', '0015_alter_video_size_bytes'),
        ('static_assets', '0004_squashed_0010_alter_fields_in_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageBackend',
            new_name='StorageLocation',
        ),
        migrations.RenameField(
            model_name='staticasset',
            old_name='storage_backend',
            new_name='storage_location',
        ),
    ]
