# Generated by Django 3.0.8 on 2020-07-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0011_squashed_0012_rename_storage_backend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='staticassets_image',
        ),
        migrations.AlterModelTable(
            name='license',
            table='staticassets_license',
        ),
        migrations.AlterModelTable(
            name='staticasset',
            table='staticassets_staticasset',
        ),
        migrations.AlterModelTable(
            name='storagelocation',
            table='staticassets_storagelocation',
        ),
        migrations.AlterModelTable(
            name='video',
            table='staticassets_video',
        ),
    ]
