# Generated by Django 3.0.8 on 2020-07-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0012_rename_db_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='license',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staticasset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='storagelocation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
