# Generated by Django 3.0.8 on 2020-07-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0013_rename_db_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='static_assets', to='static_assets.StorageLocation'),
        ),
    ]
