# Generated by Django 3.0.8 on 2020-07-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('static_assets', '0014_storage_on_delete_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The actual author of the artwork/learning materials', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_assets', to=settings.AUTH_USER_MODEL, verbose_name='author (optional)'),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
