# Generated by Django 3.0.9 on 2020-09-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0016_static_asset_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(model_name='image', name='date_created',),
        migrations.RemoveField(model_name='image', name='date_updated',),
        migrations.RemoveField(model_name='video', name='date_created',),
        migrations.RemoveField(model_name='video', name='date_updated',),
    ]
