# Generated by Django 3.0.9 on 2020-09-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0017_drop_redundant_fields'),
    ]

    operations = [
        migrations.RunSQL(
            r'''
        update static_assets_staticasset
        set thumbnail = regexp_replace(thumbnail, '[_/]*(\w{2})/(\w+)\.(\w+)', '\1/\2/\2.\3')
        where thumbnail like '_/%/%.%'
        '''
        ),
        migrations.RunSQL(
            r'''
        update static_assets_staticasset
        set thumbnail = regexp_replace(thumbnail, '[_/]*(\w{2})(\w+)\.(\w+)', '\1/\1\2/\1\2.\3')
        where thumbnail like '_/%.%'
        '''
        ),
        migrations.RunSQL(
            r'''
        update static_assets_staticasset
        set source = regexp_replace(source, '[_/]*(\w{2})/(\w+)([0-9a-z-]*)\.(\w+)', '\1/\2/\2\3.\4')
        where source like '_/%/%.%'
        '''
        ),
        migrations.RunSQL(
            r'''
        update static_assets_staticasset
        set source = regexp_replace(source, '[_/]*(\w{2})(\w+)([0-9a-z-]*)\.(\w+)', '\1/\1\2/\1\2\3.\4')
        where source not like '_/%/%.%' and source like '_/%'
        '''
        ),
    ]
