# Generated by Django 3.0.9 on 2020-09-23 07:43

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0018_normalise_file_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='source',
            field=models.FileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
