# Generated by Django 3.0.10 on 2020-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0019_update_file_fields'),
    ]

    operations = [
        migrations.RemoveField(model_name='staticasset', name='storage_location',),
    ]
