# Generated by Django 3.0.9 on 2020-10-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('static_assets', '0020_remove_storage_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('position', models.DurationField(help_text='[DD] [[HH:]MM:]ss[.uuuuuu]')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='video_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress',
                        to='static_assets.Video',
                    ),
                ),
            ],
        ),
        # Commented because we moved an existing model across application and the constraint
        # does not need to be renamed
        # migrations.AddConstraint(
        #     model_name='uservideoprogress',
        #     constraint=models.UniqueConstraint(
        #         fields=('user', 'video'), name='unique_progress_per_user_and_video'
        #     ),
        # ),
    ]
