# Generated by Django 3.0.9 on 2020-10-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0021_training_static_assets_refactor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uservideoprogress',
            constraint=models.UniqueConstraint(
                fields=('user', 'video'), name='unique_progress_per_user_and_video'
            ),
        ),
    ]
