# Generated by Django 3.0.9 on 2020-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0022_section_static_asset_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticasset', name='slug', field=models.SlugField(blank=True),
        ),
    ]
