# Generated by Django 3.0.9 on 2020-10-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0023_add_legacy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticasset',
            name='content_type',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
