# Generated by Django 3.0.9 on 2020-10-19 01:57

import common.upload_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0024_staticasset_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image', old_name='resolution', new_name='resolution_label',
        ),
        migrations.RenameField(
            model_name='video', old_name='resolution', new_name='resolution_label',
        ),
        migrations.RemoveField(model_name='image', name='resolution_text',),
        migrations.RemoveField(model_name='video', name='resolution_text',),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='source',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.CreateModel(
            name='VideoVariation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_label', models.CharField(blank=True, max_length=32)),
                (
                    'source',
                    models.FileField(
                        blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
                    ),
                ),
                ('size_bytes', models.BigIntegerField(editable=False)),
                ('content_type', models.CharField(blank=True, max_length=256)),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='variations',
                        to='static_assets.Video',
                    ),
                ),
            ],
        ),
    ]
