# Generated by Django 3.0.9 on 2020-10-19 23:57

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0025_video_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='source',
            field=models.FileField(
                blank=True, max_length=256, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AlterField(
            model_name='staticasset',
            name='thumbnail',
            field=models.FileField(
                blank=True, max_length=256, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AlterField(
            model_name='videovariation',
            name='source',
            field=models.FileField(
                blank=True, max_length=256, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
    ]
