# Generated by Django 3.0.9 on 2020-10-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0026_increase_file_field_max_lenght'),
    ]

    operations = [
        migrations.AlterModelOptions(name='staticasset', options={'ordering': ['-date_created']},),
    ]
