# Generated by Django 3.0.9 on 2020-12-07 13:20

import common.storage
import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='source',
            field=models.FileField(blank=True, max_length=256, storage=common.storage.S3Boto3CustomStorage(), upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
