"""Custom file storage classes."""
from storages.backends.s3boto3 import S3Boto3Storage


class S3PublicStorage(S3Boto3Storage):
    """Disable signing for URLs generated by this storage.

    Useful for files that are publicly readable and don't need signed URLs, such as thumbnails.
    """

    querystring_auth = False
