# Generated by Django 3.0 on 2020-02-26 10:50
from pathlib import Path

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def video_upload_path(video: 'Video', filename: str) -> str:
    return str(
        Path('trainings')
        / str(video.section.chapter.training.id)
        / 'chapters'
        / str(video.section.chapter.index)
        / 'sections'
        / str(video.section.index)
        / 'video'
        / filename
    )


def asset_upload_path(asset: 'Asset', filename: str) -> str:
    return str(
        Path('trainings')
        / str(asset.section.chapter.training.id)
        / 'chapters'
        / str(asset.section.chapter.index)
        / 'sections'
        / str(asset.section.index)
        / 'assets'
        / filename
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                (
                    'chapter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sections',
                        to='training.Chapter',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                (
                    'status',
                    models.TextField(
                        choices=[('published', 'Published'), ('unpublished', 'Unpublished')]
                    ),
                ),
                (
                    'type',
                    models.TextField(
                        choices=[
                            ('workshop', 'Workshop'),
                            ('course', 'Course'),
                            ('production_lesson', 'Production Lesson'),
                        ]
                    ),
                ),
                (
                    'difficulty',
                    models.TextField(
                        choices=[
                            ('beginner', 'Beginner'),
                            ('intermediate', 'Intermediate'),
                            ('advanced', 'Advanced'),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=video_upload_path)),
                ('size', models.IntegerField()),
                ('duration', models.DurationField()),
                (
                    'section',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='video',
                        to='training.Section',
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('position', models.DurationField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='video_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress',
                        to='training.Video',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserSectionProgress',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress',
                        to='training.Section',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='section_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='training.Tag'
                    ),
                ),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='training.Training'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='tags',
            field=models.ManyToManyField(
                related_name='trainings', through='training.TrainingTag', to='training.Tag'
            ),
        ),
        migrations.CreateModel(
            name='SectionComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'comment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'
                    ),
                ),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='training.Section'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='comments',
            field=models.ManyToManyField(
                related_name='section', through='training.SectionComment', to='comments.Comment'
            ),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to='training.Training',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chapters',
                to='training.Training',
            ),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=asset_upload_path)),
                ('size', models.IntegerField()),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assets',
                        to='training.Section',
                    ),
                ),
            ],
            options={'abstract': False,},
        ),
        migrations.AddConstraint(
            model_name='uservideoprogress',
            constraint=models.UniqueConstraint(
                # Renamed here, because the constraint had moved elsewhere
                fields=('user', 'video'), name='unique_progress_per_user_and_video_'
            ),
        ),
        migrations.AddConstraint(
            model_name='usersectionprogress',
            constraint=models.UniqueConstraint(
                fields=('user', 'section'), name='unique_progress_per_user_and_section'
            ),
        ),
        migrations.AddConstraint(
            model_name='trainingtag',
            constraint=models.UniqueConstraint(
                fields=('training', 'tag'), name='unique_tags_per_training'
            ),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(
                fields=['status', 'type', 'difficulty'], name='training_tr_status_13feb6_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(
                fields=['status', 'difficulty', 'type'], name='training_tr_status_0892b5_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='sectioncomment',
            constraint=models.UniqueConstraint(
                fields=('section', 'comment'), name='unique_section_comment'
            ),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(
                fields=('chapter', 'index'), name='unique_index_per_section'
            ),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('user', 'training'), name='unique_favourite_per_user_and_training'
            ),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(
                fields=('training', 'index'), name='unique_index_per_chapter'
            ),
        ),
    ]
