# Generated by Django 3.0.9 on 2020-12-18 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('static_assets', '0002_auto_20201218_1135'),
        ('comments', '0002_auto_20201218_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersectionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingflatpage',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='static_assets.StaticAsset'),
        ),
        migrations.AddField(
            model_name='trainingflatpage',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatpages', to='training.Training'),
        ),
        migrations.AddField(
            model_name='training',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='_section_attachments_+', to='static_assets.StaticAsset'),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='training.Chapter'),
        ),
        migrations.AddField(
            model_name='section',
            name='comments',
            field=models.ManyToManyField(related_name='section', through='training.SectionComment', to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='section',
            name='static_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='static_assets.StaticAsset'),
        ),
        migrations.AddField(
            model_name='section',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='training.Training'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='training.Training'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usersectionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'section'), name='unique_progress_per_user_and_section'),
        ),
        migrations.AddConstraint(
            model_name='trainingflatpage',
            constraint=models.UniqueConstraint(fields=('slug', 'training'), name='unique_training_flat_page_url'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['is_published', 'type', 'difficulty'], name='training_tr_is_publ_57b014_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['is_published', 'difficulty', 'type'], name='training_tr_is_publ_417c14_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectioncomment',
            constraint=models.UniqueConstraint(fields=('comment',), name='unique_section_per_comment'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'training'), name='unique_favourite_per_user_and_training'),
        ),
    ]
