# Generated by Django 3.0 on 2020-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_unique_section_per_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoprogress',
            name='position',
            field=models.DurationField(help_text='[DD] [[HH:]MM:]ss[.uuuuuu]'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(help_text='[DD] [[HH:]MM:]ss[.uuuuuu]'),
        ),
    ]
