# Generated by Django 3.0.9 on 2021-08-11 14:34

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20201218_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='picture_header',
            field=models.FileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
