# Generated by Django 3.0 on 2020-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_help_text_to_duration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter', name='slug', field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section', name='slug', field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='training', name='slug', field=models.SlugField(blank=True, unique=True),
        ),
    ]
