# Generated by Django 3.0.14 on 2021-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_chapter_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='preview_youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
