# Generated by Django 3.0 on 2020-03-01 18:39
from pathlib import Path

from django.db import migrations, models


def training_overview_upload_path(training: 'Training', filename: str) -> str:
    return str(Path('trainings') / str(training.id) / 'overview' / filename)


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_set_slug_fields_to_slugified_name_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='picture_16_9',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=training_overview_upload_path,
            ),
        ),
        migrations.AddField(
            model_name='training',
            name='picture_header',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=training_overview_upload_path,
            ),
        ),
    ]
