# Generated by Django 3.0 on 2020-03-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_pictures_for_training_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('training', 'slug'), name='unique_slug_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_slug_per_section'),
        ),
    ]
