# Generated by Django 3.0.14 on 2021-11-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_modify_content_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingflatpage',
            old_name='html_content',
            new_name='content_html',
        ),
    ]
