# Generated by Django 3.0.4 on 2020-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_change_file_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
