# Generated by Django 3.0.4 on 2020-06-14 15:35

import assets.models.assets
import common.upload_paths
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_change_training_name_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='storage',
            new_name='storage_backend',
        ),
        migrations.AlterField(
            model_name='training',
            name='picture_16_9',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='training',
            name='picture_header',
            field=assets.models.assets.DynamicStorageFileField(blank=True, null=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
