# Generated by Django 3.0.4 on 2020-06-14 15:52

import assets.models.assets
import common.upload_paths
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_rename_storage_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=assets.models.assets.DynamicStorageFileField(upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
