# Generated by Django 3.0.4 on 2020-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_add_storage_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
