# Generated by Django 3.0.8 on 2020-07-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_training_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='size',
            new_name='size_bytes',
        ),
    ]
