# Generated by Django 3.0.8 on 2020-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_rename_video_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='size_bytes',
            field=models.BigIntegerField(editable=False),
        ),
    ]
