# Generated by Django 3.0.8 on 2020-07-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_alter_video_size_bytes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='storage_backend',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='storage_backend',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='storage_backend',
            new_name='storage_location',
        ),
    ]
