# Generated by Django 3.0.9 on 2020-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_tags_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='section', name='is_free', field=models.BooleanField(default=False),
        ),
    ]
