# Generated by Django 3.0.9 on 2020-08-24 15:59

import common.upload_paths
from django.db import migrations
import static_assets.models.static_assets


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_section_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='picture_16_9',
        ),
        migrations.AddField(
            model_name='training',
            name='thumbnail',
            field=static_assets.models.static_assets.DynamicStorageFileField(default='', upload_to=common.upload_paths.get_upload_to_hashed_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='picture_header',
            field=static_assets.models.static_assets.DynamicStorageFileField(default='', upload_to=common.upload_paths.get_upload_to_hashed_path),
            preserve_default=False,
        ),
    ]
