# Generated by Django 3.0.9 on 2020-10-18 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0020_remove_storage_location_fields'),
        ('training', '0025_remove_storage_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='static_asset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sections',
                to='static_assets.StaticAsset',
            ),
        ),
    ]
