# Generated by Django 3.0.9 on 2020-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_add_static_asset'),
    ]

    operations = [
        migrations.RemoveField(model_name='uservideoprogress', name='user',),
        migrations.RemoveField(model_name='uservideoprogress', name='video',),
        migrations.RemoveField(model_name='video', name='section',),
        migrations.DeleteModel(name='Asset',),
        migrations.DeleteModel(name='UserVideoProgress',),
        migrations.DeleteModel(name='Video',),
    ]
