# Generated by Django 3.0.9 on 2020-10-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0022_section_static_asset_one_to_one'),
        ('training', '0027_training_static_assets_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='static_asset',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='section',
                to='static_assets.StaticAsset',
            ),
        ),
    ]
