# Generated by Django 3.0.9 on 2020-10-18 21:09

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_section_static_asset_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='picture_header',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AlterField(
            model_name='training',
            name='thumbnail',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
    ]
