# Generated by Django 3.0.9 on 2020-10-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_nullable_file_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(name='chapter', options={'ordering': ['index', 'name']},),
        migrations.RemoveConstraint(model_name='chapter', name='unique_index_per_chapter',),
        migrations.RemoveConstraint(model_name='chapter', name='unique_slug_per_chapter',),
        migrations.AlterField(
            model_name='chapter', name='slug', field=models.SlugField(unique=True),
        ),
    ]
