# Generated by Django 3.0.9 on 2020-10-18 23:57

import common.upload_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0030_update_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter', name='description', field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='thumbnail',
            field=models.FileField(
                blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path
            ),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
