# Generated by Django 3.0.9 on 2020-10-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0031_update_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(name='section', options={'ordering': ['index', 'name']},),
        migrations.RemoveConstraint(model_name='section', name='unique_index_per_section',),
        migrations.RemoveConstraint(model_name='section', name='unique_slug_per_section',),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='section', name='slug', field=models.SlugField(unique=True),
        ),
    ]
