# Generated by Django 3.0.9 on 2020-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
        ('training', '0033_default_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attachments',
            field=models.ManyToManyField(
                blank=True, related_name='_section_attachments_+', to='static_assets.StaticAsset'
            ),
        ),
    ]
