# Generated by Django 3.0.9 on 2020-10-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section', name='text', field=models.TextField(blank=True),
        ),
    ]
