# Generated by Django 3.0.9 on 2020-10-25 16:54

from django.db import migrations, models


def set_is_published(apps, schema_editor):
    Section = apps.get_model('training', 'Section')
    for section in Section.objects.all().iterator():
        section.is_published = section.chapter.training.status == 'published'
        section.save(update_fields=['is_published'])

    Chapter = apps.get_model('training', 'Chapter')
    for chapter in Chapter.objects.all().iterator():
        chapter.is_published = chapter.training.status == 'published'
        chapter.save(update_fields=['is_published'])


def reverse_func(apps, schema_editor):
    pass  # Nothing do to


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_optional_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter', name='is_published', field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section', name='is_published', field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_published, reverse_func),
    ]
