# Generated by Django 3.0.9 on 2020-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0036_add_is_published_to_sections_and_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='section', name='is_featured', field=models.BooleanField(default=False),
        ),
    ]
