# Generated by Django 3.0.9 on 2020-11-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0027_sorting'),
        ('training', '0037_add_is_featured_to_training_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingFlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='It will be displayed as the section name in the navigation bar.', max_length=50, verbose_name='Page title')),
                ('slug', models.SlugField(blank=True, help_text='The page slug has to be unique per training. If it is not filled, it will be the slugified page title.', verbose_name='Page slug')),
                ('content', models.TextField(blank=True, help_text='Format the content in <a href="https://commonmark.org/help/">Markdown</a>.')),
                ('html_content', models.TextField(blank=True, editable=False)),
                ('attachments', models.ManyToManyField(blank=True, to='static_assets.StaticAsset')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatpages', to='training.Training')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingflatpage',
            constraint=models.UniqueConstraint(fields=('slug', 'training'), name='unique_training_flat_page_url'),
        ),
    ]
