# Generated by Django 3.0.9 on 2020-11-02 11:24

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_add_flatpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingflatpage',
            name='header',
            field=models.FileField(blank=True, upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
