# Generated by Django 3.0.9 on 2020-11-04 10:20

from django.db import migrations, models


def set_is_published(apps, schema_editor):
    Training = apps.get_model('training', 'Training')
    for training in Training.objects.all().iterator():
        training.is_published = training.status == 'published'
        training.save(update_fields=['is_published'])


def reverse_func(apps, schema_editor):
    pass  # Nothing do to


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_add_flatpage_header'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='training',
            name='training_tr_status_13feb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='training',
            name='training_tr_status_0892b5_idx',
        ),
        migrations.AddField(
            model_name='training',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_published, reverse_func),
        migrations.RemoveField(
            model_name='training',
            name='status',
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['is_published', 'type', 'difficulty'], name='training_tr_is_publ_57b014_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['is_published', 'difficulty', 'type'], name='training_tr_is_publ_417c14_idx'),
        ),
    ]
